/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : thirdpart/hython.g
 *     -                            On : 2021-02-06 15:46:06
 *     -                for the parser : hythonParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
hythonParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef phythonParser, which is returned from a call to hythonParserNew().
 *
 * The methods in phythonParser are  as follows:
 *
 *  - 
 hythonParser_defid_expr_return
      phythonParser->defid_expr(phythonParser)
 *  - 
 hythonParser_defid_return
      phythonParser->defid(phythonParser)
 *  - 
 hythonParser_expr_return
      phythonParser->expr(phythonParser)
 *  - 
 hythonParser_multExpr_return
      phythonParser->multExpr(phythonParser)
 *  - 
 hythonParser_atom_return
      phythonParser->atom(phythonParser)
 *  - 
 hythonParser_array_atom_return
      phythonParser->array_atom(phythonParser)
 *  - 
 hythonParser_exprs_return
      phythonParser->exprs(phythonParser)
 *  - 
 hythonParser_const_value_return
      phythonParser->const_value(phythonParser)
 *  - 
 hythonParser_if_expr_return
      phythonParser->if_expr(phythonParser)
 *  - 
 hythonParser_case_expr_return
      phythonParser->case_expr(phythonParser)
 *  - 
 hythonParser_default_expr_return
      phythonParser->default_expr(phythonParser)
 *  - 
 hythonParser_switch_expr_return
      phythonParser->switch_expr(phythonParser)
 *  - 
 hythonParser_for_expr_return
      phythonParser->for_expr(phythonParser)
 *  - 
 hythonParser_while_expr_return
      phythonParser->while_expr(phythonParser)
 *  - 
 hythonParser_init_expr_return
      phythonParser->init_expr(phythonParser)
 *  - 
 hythonParser_for_do_expr_return
      phythonParser->for_do_expr(phythonParser)
 *  - 
 hythonParser_condition_expr_return
      phythonParser->condition_expr(phythonParser)
 *  - 
 hythonParser_andExpr_return
      phythonParser->andExpr(phythonParser)
 *  - 
 hythonParser_cmp_atom_return
      phythonParser->cmp_atom(phythonParser)
 *  - 
 hythonParser_cond_atom_return
      phythonParser->cond_atom(phythonParser)
 *  - 
 hythonParser_block_return
      phythonParser->block(phythonParser)
 *  - 
 hythonParser_block_expr_return
      phythonParser->block_expr(phythonParser)
 *  - 
 hythonParser_print_atom_return
      phythonParser->print_atom(phythonParser)
 *  - 
 hythonParser_def_stmt_return
      phythonParser->def_stmt(phythonParser)
 *  - 
 hythonParser_expr_stmt_return
      phythonParser->expr_stmt(phythonParser)
 *  - 
 hythonParser_control_stmt_return
      phythonParser->control_stmt(phythonParser)
 *  - 
 hythonParser_stmt_return
      phythonParser->stmt(phythonParser)
 *  - 
 hythonParser_prog_return
      phythonParser->prog(phythonParser)
 * 
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_hythonParser_H
#define _hythonParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct hythonParser_Ctx_struct hythonParser, * phythonParser;



    #include <assert.h>


#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */

typedef struct hythonParser_defid_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_defid_expr_return;



typedef struct hythonParser_defid_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_defid_return;



typedef struct hythonParser_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_expr_return;



typedef struct hythonParser_multExpr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_multExpr_return;



typedef struct hythonParser_atom_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_atom_return;



typedef struct hythonParser_array_atom_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_array_atom_return;



typedef struct hythonParser_exprs_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_exprs_return;



typedef struct hythonParser_const_value_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_const_value_return;



typedef struct hythonParser_if_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_if_expr_return;



typedef struct hythonParser_case_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_case_expr_return;



typedef struct hythonParser_default_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_default_expr_return;



typedef struct hythonParser_switch_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_switch_expr_return;



typedef struct hythonParser_for_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_for_expr_return;



typedef struct hythonParser_while_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_while_expr_return;



typedef struct hythonParser_init_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_init_expr_return;



typedef struct hythonParser_for_do_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_for_do_expr_return;



typedef struct hythonParser_condition_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_condition_expr_return;



typedef struct hythonParser_andExpr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_andExpr_return;



typedef struct hythonParser_cmp_atom_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_cmp_atom_return;



typedef struct hythonParser_cond_atom_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_cond_atom_return;



typedef struct hythonParser_block_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_block_return;



typedef struct hythonParser_block_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_block_expr_return;



typedef struct hythonParser_print_atom_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_print_atom_return;



typedef struct hythonParser_def_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_def_stmt_return;



typedef struct hythonParser_expr_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_expr_stmt_return;



typedef struct hythonParser_control_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_control_stmt_return;



typedef struct hythonParser_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_stmt_return;



typedef struct hythonParser_prog_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    hythonParser_prog_return;




/** Context tracking structure for 
hythonParser

 */
struct hythonParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     hythonParser_defid_expr_return
     (*defid_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_defid_return
     (*defid)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_expr_return
     (*expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_multExpr_return
     (*multExpr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_atom_return
     (*atom)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_array_atom_return
     (*array_atom)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_exprs_return
     (*exprs)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_const_value_return
     (*const_value)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_if_expr_return
     (*if_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_case_expr_return
     (*case_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_default_expr_return
     (*default_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_switch_expr_return
     (*switch_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_for_expr_return
     (*for_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_while_expr_return
     (*while_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_init_expr_return
     (*init_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_for_do_expr_return
     (*for_do_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_condition_expr_return
     (*condition_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_andExpr_return
     (*andExpr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_cmp_atom_return
     (*cmp_atom)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_cond_atom_return
     (*cond_atom)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_block_return
     (*block)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_block_expr_return
     (*block_expr)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_print_atom_return
     (*print_atom)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_def_stmt_return
     (*def_stmt)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_expr_stmt_return
     (*expr_stmt)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_control_stmt_return
     (*control_stmt)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_stmt_return
     (*stmt)	(struct hythonParser_Ctx_struct * ctx);

     hythonParser_prog_return
     (*prog)	(struct hythonParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred1_hython)	(struct hythonParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct hythonParser_Ctx_struct * ctx);
    void	    (*free)   (struct hythonParser_Ctx_struct * ctx);
/* @headerFile.members() */
pANTLR3_BASE_TREE_ADAPTOR	adaptor;
pANTLR3_VECTOR_FACTORY		vectors;
/* End @headerFile.members() */
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API phythonParser hythonParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API phythonParser hythonParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__45      45
#define T__46      46
#define T__47      47
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define AND      4
#define ARRAY      5
#define ASSIGN      6
#define BLOCK      7
#define BREAK      8
#define CASE      9
#define COMMENT      10
#define CONTINUE      11
#define DEF      12
#define DEFAULT      13
#define DIV      14
#define DO      15
#define DOT      16
#define DOWHILE      17
#define ELSE      18
#define EQ      19
#define ESC_SEQ      20
#define EXPONENT      21
#define FLOAT      22
#define FOR      23
#define GE      24
#define GT      25
#define HEX_DIGIT      26
#define ID      27
#define IF      28
#define INT      29
#define LE      30
#define LITTLE      31
#define MINUS      32
#define MOD      33
#define NE      34
#define OCTAL_ESC      35
#define OR      36
#define PLUS      37
#define PRINT      38
#define STRING      39
#define SWITCH      40
#define TIMES      41
#define UNICODE_ESC      42
#define WHILE      43
#define WS      44
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for hythonParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
